name: Gradle Build Scan
on: workflow_dispatch
jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - uses: actions/setup-java@9b86bbe88a8152e5b9e6c15fd2e0efdd2994ffb6
        with:
          java-version: 8
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Scan
        run: ./gradlew build --scan